services:
  video-app:
    build: .
    network_mode: "host"
    # Mapeamos las carpetas de datos para que los renders se guarden en tu máquina host
    volumes:
      - ./data:/app/data
      - ./examples:/app/examples
      - .:/app
    env_file:
      - .env
